### ISSUE TITLE
CyclicBarrier vs CountDownLatch

### ISSUE THREAD

**Issue by zhamri** [STIW3054-A201/Main-Issues#13]
## Instruction:

1. Test the source code of __CyclicBarrier__ (Question 6) from the link below.

    https://github.com/zhamri/MyClass-STIW3054/wiki/Example-of-Questions

1. Run the source code __FIVE (5)__ times and see the differences.

1. Test the source code of __CountDownLatch__ from the link below.

    https://github.com/zhamri/MyClass-STIW3054/blob/master/src/main/java/com/stiw3054/CountDownLatch/E1/App.java

1. Run the source code __FIVE (5)__ times and see the differences.

1. Then search __ONE (1)__ video on YouTube and __ONE (1)__ website about __CyclicBarrier__ and __CountDownLatch__ in Java. 

1. Give your opinion about the difference between __CyclicBarrier__ and __CountDownLatch__?

**Comment by nazirahramli** [comment]
Youtube:  https://www.youtube.com/watch?v=Jzh3ZQc2kb8&ab_channel=AmitSrivastava
Website: https://www.java67.com/2015/06/how-to-use-cyclicbarrier-in-java.html

CountDownLatch is a synchronization aid that allows one or more threads to wait until a set of operations being performed in other threads completes.
CyclicBarrier is a synchronization aid that allows a set of threads to all wait for each other to reach a common barrier point.

**Comment by rudflinarafiqa** [comment]
Youtube - https://www.youtube.com/watch?v=aXquiU12A4g
Website - https://www.baeldung.com/java-cyclicbarrier-countdownlatch

CountDownLatch is a construct that a thread waits on while other threads count down on the latch until it reaches zero.
CyclicBarrier is a reusable construct where a group of threads waits together until all of the threads arrive. At that point, the barrier is broken and an action can optionally be taken.

**Comment by gibrail-fikri** [comment]
Video: https://www.youtube.com/watch?v=J3QZ5gfCtAg
Website: https://knpcode.com/java/concurrency/difference-between-countdownlatch-and-cyclicbarrier-in-java/

CyclicBarrier allows a set of threads to wait for each other before making further progress
CountDownLatch allows one or more thread to wait for operations performed in other threads to complete

**Comment by norfatiah** [comment]
Video: https://www.youtube.com/watch?v=YvuhBbl0u88
Website: https://www.baeldung.com/java-cyclicbarrier-countdownlatch#:~:text=As%20stated%20in%20the%20definitions,maintains%20a%20count%20of%20tasks.

Difference between CountDownLatch and CyclicBarrier is, CountDownLatch cannot be reused, when count arrives at zero it can’t be reset while CyclicBarrier can be reused after holding threads are released.

**Comment by najihahFz** [comment]
Youtube : https://www.youtube.com/watch?v=J3QZ5gfCtAg&feature=youtu.be
Website : https://www.java67.com/2012/08/difference-between-countdownlatch-and-cyclicbarrier-java.html

CountDownLatch is a construct that a thread waits on while other threads count down on the latch until it reaches zero.
CyclicBarrier is a reusable construct where a group of threads waits together until all of the threads arrive.

**Comment by youyc** [comment]
Youtube: https://www.youtube.com/watch?v=aXquiU12A4g

Website : https://www.baeldung.com/java-cyclicbarrier-countdownlatch#:~:text=As%20stated%20in%20the%20definitions,maintains%20a%20count%20of%20tasks.

Difference between CyclicBarrier and CountDownLatch

CountDownLatch − A synchronization aid that allows one or more threads to wait until a set of operations being performed in other threads completes. 
CyclicBarrier − A synchronization aid that allows a set of threads to all wait for each other to reach a common barrier point.

**Comment by MifzalAqmar** [comment]
Youtube: https://www.youtube.com/watch?v=9Z9tkwVFGko

Website: https://www.geeksforgeeks.org/countdownlatch-in-java/

Difference:
Cannot reuse same CountDownLatch instance once count reaches to zero and latch is open, but, CyclicBarrier can be reused by resetting Barrier, once broken.
